name: onlinerentalapp
description: A new Flutter application.


dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  firebase_auth: ^0.15.3+1
#  cloud_firestore: ^0.8.2+3
  cloud_firestore_all: ^0.1.1+4
  location: ^2.3.5
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  provider: ^4.0.2
  flutter_spinkit: ^4.1.1+1
  firebase_database: ^3.1.1
  rxdart: ^0.23.1
  geoflutterfire: ^2.0.3+8
  google_maps_flutter:
  uuid: ^2.0.4
  image_picker: ^0.6.3+1
  curved_navigation_bar: ^0.3.1
  intl: ^0.16.1
  firebase_storage: ^3.1.1
  url_launcher: ^5.4.1
  http: ^0.12.0+4
  webfeed: ^0.4.2
  cached_network_image: ^2.0.0
  firebase_ml_vision: ^0.9.3+5
  tflite: ^1.0.4
  image: ^2.1.4
  wave: ^0.0.8
  date_format: ^1.0.8
  timeago: ^2.0.10
  firebase_messaging: ^6.0.12
  google_sign_in: ^4.1.4
  flutter_svg: ^0.17.2
  animator: ^1.0.0+5
  google_maps_webservice: ^0.0.16
  random_string: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/manformalpose.jpg
    - images/femaleformalpose.jpg
    - images/dresspose.jpg
    - images/stageclothespose.jpg
    - images/guitar.jpg
    - images/manformal.jpg
    - images/femaleformal.jpeg
    - images/weedingdress.png
    - images/traditionaljapan.png
    - images/drum.png
    - images/bowtie.jpg
    - images/dressprod.jpg
    - images/menshoes.png
    - images/womenheels.jpg
    - images/blackdress.jpg
    - images/Formalmenclothes.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
